platform :ios, '7.0'
inhibit_all_warnings!

pod 'IQKeyboardManager', '~> 3.2.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Masonry', '~> 0.6.2'
pod 'MJExtension', '~> 2.5.9'
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'ReactiveCocoa', '2.5'
pod 'FMDB'
pod 'Aspects', '~> 1.4.1'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'SDWebImage', '~> 3.8.1'
pod 'SDCycleScrollView','~> 1.61'

