
platform :ios, '7.0'
inhibit_all_warnings!

pod 'IQKeyboardManager', '~> 3.2.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Masonry', '~> 0.6.2'
pod 'MJExtension', '~> 2.5.9'
pod 'MJRefresh', '~> 2.4.7'
pod 'AFNetworking', '~> 2.6.0’
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3' 
pod 'Nimbus/AttributedLabel', :head
pod 'ReactiveCocoa', '2.5'
pod 'FMDB'
pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'
pod 'Aspects', '~> 1.4.1'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'LGDrawer', '~> 1.0.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'Mantle', '~> 1.5.5'

