

platform :ios, '7.0'
inhibit_all_warnings!

target :WeimiSP do

pod 'IQKeyboardManager', '~> 3.2.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Masonry', '~> 0.6.2'
pod 'MJExtension', '~> 2.5.9'
pod 'MJRefresh', '~> 2.4.7'
pod 'AFNetworking', '~> 2.6.0'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3' 
pod 'ReactiveCocoa', '2.5'
pod 'FMDB'
pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'
pod 'Aspects', '~> 1.4.1'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'LGDrawer', '~> 1.0.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'Mantle', '~> 1.5.5'
pod 'OAStackView', '~> 0.1.0'
pod 'ZipArchive', '~> 1.4.0'
pod 'JSONModel', '~> 1.1.0'
pod 'AlipaySDK-2.0', '~> 2.0.3'
pod 'Reachability', '~> 3.2'
pod 'ProtocolBuffers', '~> 1.9.5'
pod 'WEMEClient', :git => 'git@git.thinker.vc:yaoweifeng/WEMEClient.git', :branch => 'master'
#pod 'YYCache', '~> 0.9.4'
#pod 'SSKeychain', '~> 1.3.1'
pod 'SVProgressHUD'
pod 'YLGIFImage'
pod 'Amr2Wav', :git => 'https://github.com/summerblue/Amr2Wav.git'

end


